"""Add enterprise task management models

Revision ID: 5a25e5c4c723
Revises: 
Create Date: 2026-03-13 21:29:05.161734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a25e5c4c723'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('template_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('workflow_template_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('current_stage_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('projects', sa.Column('key_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('projects', sa.Column('success_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('projects', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('business_unit', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('client_name', sa.String(length=200), nullable=True))
    op.add_column('projects', sa.Column('budget', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('budget_spent', sa.Float(), nullable=False))
    op.create_foreign_key(op.f('fk_projects_template_id_project_templates'), 'projects', 'project_templates', ['template_id'], ['id'])
    op.create_foreign_key(op.f('fk_projects_workflow_template_id_workflow_templates'), 'projects', 'workflow_templates', ['workflow_template_id'], ['id'])
    op.add_column('task_assignments', sa.Column('is_primary', sa.Boolean(), nullable=False))
    op.add_column('task_dependencies', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('task_dependencies', sa.Column('dependency_type', sa.Enum('BLOCKS', 'BLOCKED_BY', 'RELATES_TO', 'DUPLICATES', name='dependencytype'), nullable=False))
    op.add_column('task_dependencies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_task_dependencies_depends_on_id'), 'task_dependencies', ['depends_on_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.drop_constraint(op.f('fk_task_dependencies_depends_on_id_tasks'), 'task_dependencies', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_dependencies_task_id_tasks'), 'task_dependencies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_dependencies_depends_on_id_tasks'), 'task_dependencies', 'tasks', ['depends_on_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_task_dependencies_task_id_tasks'), 'task_dependencies', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('primary_assignee_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('priority_score', sa.Float(), nullable=False))
    op.add_column('tasks', sa.Column('workflow_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('workflow_state_id', sa.String(length=36), nullable=True))
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_primary_assignee_id'), 'tasks', ['primary_assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_reporter_id'), 'tasks', ['reporter_id'], unique=False)
    op.drop_constraint(op.f('fk_tasks_assignee_id_users'), 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_workflow_id_task_workflows'), 'tasks', 'task_workflows', ['workflow_id'], ['id'])
    op.create_foreign_key(op.f('fk_tasks_primary_assignee_id_users'), 'tasks', 'users', ['primary_assignee_id'], ['id'])
    op.create_foreign_key(op.f('fk_tasks_workflow_state_id_task_workflow_states'), 'tasks', 'task_workflow_states', ['workflow_state_id'], ['id'])
    op.drop_column('tasks', 'assignee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assignee_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_tasks_workflow_state_id_task_workflow_states'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_primary_assignee_id_users'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_workflow_id_task_workflows'), 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_assignee_id_users'), 'tasks', 'users', ['assignee_id'], ['id'])
    op.drop_index(op.f('ix_tasks_reporter_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_primary_assignee_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.drop_column('tasks', 'workflow_state_id')
    op.drop_column('tasks', 'workflow_id')
    op.drop_column('tasks', 'priority_score')
    op.drop_column('tasks', 'primary_assignee_id')
    op.drop_constraint(op.f('fk_task_dependencies_task_id_tasks'), 'task_dependencies', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_dependencies_depends_on_id_tasks'), 'task_dependencies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_dependencies_task_id_tasks'), 'task_dependencies', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('fk_task_dependencies_depends_on_id_tasks'), 'task_dependencies', 'tasks', ['depends_on_id'], ['id'])
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_depends_on_id'), table_name='task_dependencies')
    op.drop_column('task_dependencies', 'created_at')
    op.drop_column('task_dependencies', 'dependency_type')
    op.drop_column('task_dependencies', 'id')
    op.drop_column('task_assignments', 'is_primary')
    op.drop_constraint(op.f('fk_projects_workflow_template_id_workflow_templates'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_template_id_project_templates'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'budget_spent')
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'client_name')
    op.drop_column('projects', 'business_unit')
    op.drop_column('projects', 'department')
    op.drop_column('projects', 'success_criteria')
    op.drop_column('projects', 'key_results')
    op.drop_column('projects', 'objectives')
    op.drop_column('projects', 'current_stage_id')
    op.drop_column('projects', 'workflow_template_id')
    op.drop_column('projects', 'template_id')
    # ### end Alembic commands ###
