"""Schemas package."""

from app.schemas.board import (
    BoardColumnCreate,
    BoardColumnResponse,
    BoardColumnUpdate,
    BoardCreate,
    BoardDetailResponse,
    BoardResponse,
    BoardSwimlaneCreate,
    BoardSwimlaneResponse,
    BoardSwimlaneUpdate,
    BoardUpdate,
    CardMoveRequest,
)
from app.schemas.notification import (
    MarkReadRequest,
    NotificationCreate,
    NotificationListResponse,
    NotificationPreferenceResponse,
    NotificationPreferenceUpdate,
    NotificationResponse,
    NotificationUpdateRequest,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectDetailResponse,
    ProjectFilterParams,
    ProjectListResponse,
    ProjectMemberCreate,
    ProjectMemberResponse,
    ProjectMemberUpdate,
    ProjectResponse,
    ProjectUpdate,
)
from app.schemas.task import (
    TagCreate,
    TagResponse,
    TaskBatchUpdateRequest,
    TaskCommentCreate,
    TaskCommentResponse,
    TaskCommentUpdate,
    TaskCreate,
    TaskDetailResponse,
    TaskFilterParams,
    TaskListResponse,
    TaskMoveRequest,
    TaskResponse,
    TaskUpdate,
    TimeEntryCreate,
    TimeEntryResponse,
    TimeEntryUpdate,
)
from app.schemas.user import (
    ChangePasswordRequest,
    PasswordResetConfirm,
    PasswordResetRequest,
    RefreshTokenRequest,
    TokenResponse,
    UserCreate,
    UserListResponse,
    UserLoginRequest,
    UserProfileResponse,
    UserResponse,
    UserUpdate,
)
from app.schemas.landing import (
    LandingHeroResponse,
    LandingFeatureResponse,
    LandingBadgeResponse,
    PricingFeatureResponse,
    PricingTierResponse,
    FooterLinkResponse,
    FooterCategoryResponse,
    LandingContentResponse,
    LeadCaptureCreate,
    LandingLeadResponse,
)

__all__ = [
    # User schemas
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserProfileResponse",
    "UserListResponse",
    "UserLoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "ChangePasswordRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    # Project schemas
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectDetailResponse",
    "ProjectListResponse",
    "ProjectFilterParams",
    "ProjectMemberCreate",
    "ProjectMemberUpdate",
    "ProjectMemberResponse",
    # Task schemas
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskDetailResponse",
    "TaskListResponse",
    "TaskFilterParams",
    "TaskMoveRequest",
    "TaskBatchUpdateRequest",
    "TaskCommentCreate",
    "TaskCommentUpdate",
    "TaskCommentResponse",
    "TagCreate",
    "TagResponse",
    "TimeEntryCreate",
    "TimeEntryUpdate",
    "TimeEntryResponse",
    # Board schemas
    "BoardCreate",
    "BoardUpdate",
    "BoardResponse",
    "BoardDetailResponse",
    "BoardColumnCreate",
    "BoardColumnUpdate",
    "BoardColumnResponse",
    "BoardSwimlaneCreate",
    "BoardSwimlaneUpdate",
    "BoardSwimlaneResponse",
    "CardMoveRequest",
    # Notification schemas
    "NotificationCreate",
    "NotificationResponse",
    "NotificationListResponse",
    "NotificationUpdateRequest",
    "MarkReadRequest",
    "NotificationPreferenceResponse",
    "NotificationPreferenceUpdate",
    # Landing schemas
    "LandingHeroResponse",
    "LandingFeatureResponse",
    "LandingBadgeResponse",
    "PricingFeatureResponse",
    "PricingTierResponse",
    "FooterLinkResponse",
    "FooterCategoryResponse",
    "LandingContentResponse",
    "LeadCaptureCreate",
    "LandingLeadResponse",
]
